import React from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'

export default function Header () {
  return (
    <>
      <Head>
        <title>Nova Visão para Novo Tempo</title>
        <meta name="author" content="SitePoint"></meta>
        <meta name="description" content="Generated by create next app" />

        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Exo:wght@400;500;700&family=Lato:wght@300;400&display=swap" rel="stylesheet" />
      </Head>
      <header className={styles.header}>
        <div className={styles.container}>
          <div className={styles.header_content}>
            <Image src="/logo.svg" alt="Logo" width={250} height={100} />
            <nav className={styles.nav}>
              <ul>
                <li className={styles.menu_item}>
                  <a
                    className={styles.menu_link}
                    target="_blank"
                    href="https://docs.google.com/forms/d/e/1FAIpQLSdXSUvsFKFJdHkbTHInXXC_RDNfqkb1PG9slWI2HxgvDtysfQ/viewform?usp=sf_link"
                  >
                    Inscreva-se
                  </a>
                </li>
                <li className={styles.menu_item}>
                  <a
                    className={styles.menu_link}
                    href="#about"
                  >
                    Sobre
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
    </>
  )
}
